/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rafa.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.rafa.model.Celebrity;
import com.rafa.model.CelebrityModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Celebrity service. Represents a row in the &quot;celebrityData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>CelebrityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CelebrityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CelebrityImpl
 * @generated
 */
@ProviderType
public class CelebrityModelImpl
	extends BaseModelImpl<Celebrity> implements CelebrityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a celebrity model instance should use the <code>Celebrity</code> interface instead.
	 */
	public static final String TABLE_NAME = "celebrityData";

	public static final Object[][] TABLE_COLUMNS = {
		{"celebrityId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"profession", Types.VARCHAR}, {"nickName", Types.VARCHAR},
		{"country", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("celebrityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("profession", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nickName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("country", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table celebrityData (celebrityId LONG not null primary key,name VARCHAR(75) null,profession VARCHAR(75) null,nickName VARCHAR(75) null,country VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table celebrityData";

	public static final String ORDER_BY_JPQL =
		" ORDER BY celebrity.celebrityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY celebrityData.celebrityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COUNTRY_COLUMN_BITMASK = 1L;

	public static final long PROFESSION_COLUMN_BITMASK = 2L;

	public static final long CELEBRITYID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public CelebrityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _celebrityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCelebrityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _celebrityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Celebrity.class;
	}

	@Override
	public String getModelClassName() {
		return Celebrity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Celebrity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Celebrity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Celebrity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Celebrity)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Celebrity, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Celebrity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Celebrity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Celebrity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Celebrity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Celebrity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Celebrity.class.getClassLoader(), Celebrity.class,
			ModelWrapper.class);

		try {
			Constructor<Celebrity> constructor =
				(Constructor<Celebrity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Celebrity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Celebrity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Celebrity, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Celebrity, Object>>();
		Map<String, BiConsumer<Celebrity, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Celebrity, ?>>();

		attributeGetterFunctions.put("celebrityId", Celebrity::getCelebrityId);
		attributeSetterBiConsumers.put(
			"celebrityId",
			(BiConsumer<Celebrity, Long>)Celebrity::setCelebrityId);
		attributeGetterFunctions.put("name", Celebrity::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Celebrity, String>)Celebrity::setName);
		attributeGetterFunctions.put("profession", Celebrity::getProfession);
		attributeSetterBiConsumers.put(
			"profession",
			(BiConsumer<Celebrity, String>)Celebrity::setProfession);
		attributeGetterFunctions.put("nickName", Celebrity::getNickName);
		attributeSetterBiConsumers.put(
			"nickName", (BiConsumer<Celebrity, String>)Celebrity::setNickName);
		attributeGetterFunctions.put("country", Celebrity::getCountry);
		attributeSetterBiConsumers.put(
			"country", (BiConsumer<Celebrity, String>)Celebrity::setCountry);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCelebrityId() {
		return _celebrityId;
	}

	@Override
	public void setCelebrityId(long celebrityId) {
		_celebrityId = celebrityId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getProfession() {
		if (_profession == null) {
			return "";
		}
		else {
			return _profession;
		}
	}

	@Override
	public void setProfession(String profession) {
		_columnBitmask |= PROFESSION_COLUMN_BITMASK;

		if (_originalProfession == null) {
			_originalProfession = _profession;
		}

		_profession = profession;
	}

	public String getOriginalProfession() {
		return GetterUtil.getString(_originalProfession);
	}

	@Override
	public String getNickName() {
		if (_nickName == null) {
			return "";
		}
		else {
			return _nickName;
		}
	}

	@Override
	public void setNickName(String nickName) {
		_nickName = nickName;
	}

	@Override
	public String getCountry() {
		if (_country == null) {
			return "";
		}
		else {
			return _country;
		}
	}

	@Override
	public void setCountry(String country) {
		_columnBitmask |= COUNTRY_COLUMN_BITMASK;

		if (_originalCountry == null) {
			_originalCountry = _country;
		}

		_country = country;
	}

	public String getOriginalCountry() {
		return GetterUtil.getString(_originalCountry);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Celebrity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Celebrity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Celebrity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CelebrityImpl celebrityImpl = new CelebrityImpl();

		celebrityImpl.setCelebrityId(getCelebrityId());
		celebrityImpl.setName(getName());
		celebrityImpl.setProfession(getProfession());
		celebrityImpl.setNickName(getNickName());
		celebrityImpl.setCountry(getCountry());

		celebrityImpl.resetOriginalValues();

		return celebrityImpl;
	}

	@Override
	public int compareTo(Celebrity celebrity) {
		long primaryKey = celebrity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Celebrity)) {
			return false;
		}

		Celebrity celebrity = (Celebrity)obj;

		long primaryKey = celebrity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		CelebrityModelImpl celebrityModelImpl = this;

		celebrityModelImpl._originalProfession = celebrityModelImpl._profession;

		celebrityModelImpl._originalCountry = celebrityModelImpl._country;

		celebrityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Celebrity> toCacheModel() {
		CelebrityCacheModel celebrityCacheModel = new CelebrityCacheModel();

		celebrityCacheModel.celebrityId = getCelebrityId();

		celebrityCacheModel.name = getName();

		String name = celebrityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			celebrityCacheModel.name = null;
		}

		celebrityCacheModel.profession = getProfession();

		String profession = celebrityCacheModel.profession;

		if ((profession != null) && (profession.length() == 0)) {
			celebrityCacheModel.profession = null;
		}

		celebrityCacheModel.nickName = getNickName();

		String nickName = celebrityCacheModel.nickName;

		if ((nickName != null) && (nickName.length() == 0)) {
			celebrityCacheModel.nickName = null;
		}

		celebrityCacheModel.country = getCountry();

		String country = celebrityCacheModel.country;

		if ((country != null) && (country.length() == 0)) {
			celebrityCacheModel.country = null;
		}

		return celebrityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Celebrity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Celebrity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Celebrity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Celebrity)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Celebrity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Celebrity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Celebrity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Celebrity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Celebrity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _celebrityId;
	private String _name;
	private String _profession;
	private String _originalProfession;
	private String _nickName;
	private String _country;
	private String _originalCountry;
	private long _columnBitmask;
	private Celebrity _escapedModel;

}