/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rafa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Celebrity service. Represents a row in the &quot;celebrityData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.rafa.model.impl.CelebrityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.rafa.model.impl.CelebrityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Celebrity
 * @generated
 */
@ProviderType
public interface CelebrityModel extends BaseModel<Celebrity> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a celebrity model instance should use the {@link Celebrity} interface instead.
	 */

	/**
	 * Returns the primary key of this celebrity.
	 *
	 * @return the primary key of this celebrity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this celebrity.
	 *
	 * @param primaryKey the primary key of this celebrity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the celebrity ID of this celebrity.
	 *
	 * @return the celebrity ID of this celebrity
	 */
	public long getCelebrityId();

	/**
	 * Sets the celebrity ID of this celebrity.
	 *
	 * @param celebrityId the celebrity ID of this celebrity
	 */
	public void setCelebrityId(long celebrityId);

	/**
	 * Returns the name of this celebrity.
	 *
	 * @return the name of this celebrity
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this celebrity.
	 *
	 * @param name the name of this celebrity
	 */
	public void setName(String name);

	/**
	 * Returns the profession of this celebrity.
	 *
	 * @return the profession of this celebrity
	 */
	@AutoEscape
	public String getProfession();

	/**
	 * Sets the profession of this celebrity.
	 *
	 * @param profession the profession of this celebrity
	 */
	public void setProfession(String profession);

	/**
	 * Returns the nick name of this celebrity.
	 *
	 * @return the nick name of this celebrity
	 */
	@AutoEscape
	public String getNickName();

	/**
	 * Sets the nick name of this celebrity.
	 *
	 * @param nickName the nick name of this celebrity
	 */
	public void setNickName(String nickName);

	/**
	 * Returns the country of this celebrity.
	 *
	 * @return the country of this celebrity
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this celebrity.
	 *
	 * @param country the country of this celebrity
	 */
	public void setCountry(String country);

}